version: '3.7'

services:
    app:
        build: docker/php-fpm
        volumes:
            - .:/app
        env_file:
            - .env.dist
            - .env
        environment:
            - APP_SECRET=${APP_SECRET}
    server:
        build: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/app